/*
 Navicat Premium Data Transfer

 Source Server         : Archeage
 Source Server Type    : MySQL
 Source Server Version : 50632
 Source Host           : localhost:3306
 Source Schema         : archeage

 Target Server Type    : MySQL
 Target Server Version : 50632
 File Encoding         : 65001

 Date: 02/12/2018 19:09:06
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for npc_posture_sets
-- ----------------------------
DROP TABLE IF EXISTS `npc_posture_sets`;
CREATE TABLE `npc_posture_sets`  (
  `id` int(10) NOT NULL COMMENT '动作集合ID',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '动作名称',
  `quest_anim_action_id` int(10) NULL DEFAULT NULL COMMENT '动画进行ID',
  `comment` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '注释',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of npc_posture_sets
-- ----------------------------
INSERT INTO `npc_posture_sets` VALUES (1, 'stn_act_stabler_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (3, 'chair_weapon_male', 0, '무기상인');
INSERT INTO `npc_posture_sets` VALUES (4, 'stn_thinking_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (5, 'stn_crossarm_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (6, 'chair_rest_building_dealer_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (7, 'stn_stabler_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (8, 'stn_handsback_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (9, 'stn_priest_pray_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (11, 'stn_record_lookaround_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (12, 'stn_thinking_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (13, 'stn_handsback_male_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (14, 'stn_crossarm_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (15, 'stn_getherhands_female_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (16, 'stn_searching_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (17, 'sit_lean_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (19, 'stn_crossarm_material_trader_female', 0, '재료상인');
INSERT INTO `npc_posture_sets` VALUES (20, 'stn_pharmacist_female', 0, '');
INSERT INTO `npc_posture_sets` VALUES (21, 'stn_record_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (22, 'obj_chair_plant_male', 0, '묘목상인');
INSERT INTO `npc_posture_sets` VALUES (23, 'stn_handback_furniure_dealer_male', 0, '가구상인');
INSERT INTO `npc_posture_sets` VALUES (24, 'stn_crossarm_armor_dealer_male', 0, '방어구상인');
INSERT INTO `npc_posture_sets` VALUES (25, 'stn_sermon_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (26, 'obj_stn_dress_male', 0, '의상상인');
INSERT INTO `npc_posture_sets` VALUES (27, 'chair_rest_livestock_female', 0, '가축 상인');
INSERT INTO `npc_posture_sets` VALUES (28, 'stn_florist_female', 0, '씨앗상인');
INSERT INTO `npc_posture_sets` VALUES (29, 'stn_soldier_nuian_all', 0, '누이안 경비병, 감시병 -> 28번 포스쳐 여벌 남아 있음. (깃발)');
INSERT INTO `npc_posture_sets` VALUES (30, 'stn_getherhands_female', 0, '');
INSERT INTO `npc_posture_sets` VALUES (31, ' stn_crossarm_material_trader_female_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (32, 'ground_sexappeal_female', 0, '');
INSERT INTO `npc_posture_sets` VALUES (33, 'chair_temptation_female (의자 없음)', 0, '');
INSERT INTO `npc_posture_sets` VALUES (34, 'sit_torch_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (35, 'sit_prisoner_all', 0, '죄수, 포로');
INSERT INTO `npc_posture_sets` VALUES (36, 'stn_oldman_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (37, 'sit_crossleg_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (38, 'sit_drunken_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (39, 'obj_stn_cook_female', 0, '음식상인, 요리사');
INSERT INTO `npc_posture_sets` VALUES (40, 'stn_scope_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (41, 'chair_straightleg_female', 204, '');
INSERT INTO `npc_posture_sets` VALUES (42, 'stn_commander_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (43, 'stn_soldier_axe_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (45, 'chair_rest_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (47, 'ground_sleep_all(em)', 0, '');
INSERT INTO `npc_posture_sets` VALUES (48, 'sit_crouch_kid', 0, 'girl01 용');
INSERT INTO `npc_posture_sets` VALUES (49, 'sit_gang_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (50, 'sit_netting_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (51, 'stn_search_cough_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (52, 'sit_crouch_crying', 0, 'girl01 용');
INSERT INTO `npc_posture_sets` VALUES (53, 'sit_investigation_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (55, 'stn_soldier_sword_all (무기안나옴)', 0, '');
INSERT INTO `npc_posture_sets` VALUES (56, 'chair_searching_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (59, 'sit_crouch_kid_playing', 0, 'girl01 용');
INSERT INTO `npc_posture_sets` VALUES (60, 'ground_corpse_all(em)', 0, '');
INSERT INTO `npc_posture_sets` VALUES (62, 'stn_searching_all', 0, '남자 제작 예정 (9월 1주)');
INSERT INTO `npc_posture_sets` VALUES (63, 'stn_soldier_archer_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (64, 'chair_guitar_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (67, 'stn_priest_pray_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (68, 'sit_kneel_all(em)', 97, '');
INSERT INTO `npc_posture_sets` VALUES (72, 'chair_searching_all(judge)', 0, '재판관 전용 (56번과 다른 의자가 붙어 있음)');
INSERT INTO `npc_posture_sets` VALUES (73, 'chair_sleep_all', 204, '');
INSERT INTO `npc_posture_sets` VALUES (75, 'stn_soldier_elf_all', 0, '엘프 경비병, 감시병');
INSERT INTO `npc_posture_sets` VALUES (76, 'stn_soldier_hariharan_all', 0, '하리하란 경비병, 감시병');
INSERT INTO `npc_posture_sets` VALUES (77, 'stn_soldier_ferre_male', 0, '페레 경비병, 감시병');
INSERT INTO `npc_posture_sets` VALUES (78, 'stn_angry_all', 0, '어셋 제작 예정');
INSERT INTO `npc_posture_sets` VALUES (79, 'stn_afraid_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (81, 'stn_angry_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (82, 'stn_afraid_all_notalk', 97, '9월 1주차 발주 (어셋제작예정)');
INSERT INTO `npc_posture_sets` VALUES (83, 'stn_cough_kid', 0, '');
INSERT INTO `npc_posture_sets` VALUES (84, 'stn_sworddance_all', 0, 'fist_pos_stn_sdance_talk');
INSERT INTO `npc_posture_sets` VALUES (85, 'sit_beggar_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (86, 'stn_cough_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (87, 'ground_falldown_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (88, 'stn_hurray_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (89, 'stn_shoveling_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (90, 'sit_hammer_all', 97, '');
INSERT INTO `npc_posture_sets` VALUES (91, 'stn_stumble_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (92, 'stn_talk_1_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (93, 'stn_talk_2_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (94, 'stn_gang_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (95, 'stn_lonely_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (96, 'stn_loud_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (97, 'stn_sweat_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (98, 'stn_vomit_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (99, 'stn_readbook_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (100, 'stn_relaxed_a', 97, '');
INSERT INTO `npc_posture_sets` VALUES (102, 'stn_relaxed_b', 97, '');
INSERT INTO `npc_posture_sets` VALUES (103, 'stn_relaxed_c', 97, '');
INSERT INTO `npc_posture_sets` VALUES (104, 'stn_boring_all', 97, '');
INSERT INTO `npc_posture_sets` VALUES (105, 'stn_crying_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (106, 'chair_stump_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (107, 'sit_investigation_machine_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (108, 'stn_record_machine_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (109, 'chair_pink_female', 0, '');
INSERT INTO `npc_posture_sets` VALUES (110, 'stn_calling_all', 97, 'fist_pos_stn_calling_idle');
INSERT INTO `npc_posture_sets` VALUES (111, 'stn_shoveling_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (112, 'stn_peep_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (113, 'stn_peep_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (114, 'stn_singing_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (115, 'stn_singing_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (116, 'stn_shy_kid_notalk', 97, 'girl01/narayana_girl01 용');
INSERT INTO `npc_posture_sets` VALUES (117, 'sit_crouch_crying_kid', 0, '');
INSERT INTO `npc_posture_sets` VALUES (118, 'sit_crouch_crying_kid_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (119, 'sit_crouch_kid_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (120, 'sit_crouch_kid_playing_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (121, 'stn_anvil_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (122, 'ground_sidesleep_all ', 0, 'fist_pos_gnd_sidesleep_talk');
INSERT INTO `npc_posture_sets` VALUES (123, 'stn_onshoulder_Pickaxe_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (124, 'stn_onshoulder_fishingrod_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (125, 'sit_chair_tapswaits_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (126, 'sit_chair_snooze_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (127, 'sit_chair_crossleg_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (128, 'stn_pickaxe_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (129, 'stn_fishingrod_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (130, 'hang_prisoner_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (131, 'stn_playlute_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (132, 'stn_playpipe_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (133, 'stn_soldier_hariharan_female', 0, '');
INSERT INTO `npc_posture_sets` VALUES (134, 'stn_soldier_nuian_female', 0, '');
INSERT INTO `npc_posture_sets` VALUES (135, 'stn_soldier_elf_female', 0, '');
INSERT INTO `npc_posture_sets` VALUES (136, 'stn_soldier_ferre_female', 0, '');
INSERT INTO `npc_posture_sets` VALUES (137, 'pos_sit_pulling', 97, '');
INSERT INTO `npc_posture_sets` VALUES (139, 'chair_oldman_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (142, 'stn_liabilities_b_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (143, 'stn_fishing_male_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (144, 'chair_readbook_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (145, 'gnd_corpse_lastwill_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (146, 'stn_guitarist_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (147, 'chair_armrest_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (148, 'stn_crossarm_blackguard_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (149, 'stn_crossarm_blackguard_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (150, 'stn_cleaning_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (151, 'sit_chair_stump_crossleg_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (152, 'stn_stumble_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (153, 'chair_aptchair_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (154, 'chair_crossleg_aptchair_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (155, 'chair_crossleg_elf_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (156, 'chair_crossleg_elf_02_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (157, 'chair_armrest_oscar_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (158, 'sit_netting_male(net)', 0, '');
INSERT INTO `npc_posture_sets` VALUES (159, 'chair_armrest_b_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (160, 'stn_onehand_ax01_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (161, 'stn_onehand_ax01_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (162, 'stn_onehand_trowel01_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (163, 'stn_onehand_trowel01_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (164, 'stn_onehand_relaxed_blade_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (165, 'stn_onehand_relaxed_blade_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (166, 'fist_pos_stn_onehand_bow_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (167, 'fist_pos_stn_onehand_bow_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (168, 'stn_sprinklewater_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (169, 'stn_sprinklewater_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (170, 'stn_get_fruit_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (171, 'stn_get_fruit_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (172, 'sit_feeding_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (173, 'sit_feeding_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (174, 'stn_act_stabler_male_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (175, 'stn_cleaning_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (176, 'stn_florist_female_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (177, 'stn_liabilities_c_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (179, 'stn_liabilities_d_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (180, 'stn_onehand_relaxed_lamp_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (181, 'stn_onehand_relaxed_lamp_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (182, 'stn_shy_kid', 0, '');
INSERT INTO `npc_posture_sets` VALUES (183, 'stn_distract_kid', 0, '');
INSERT INTO `npc_posture_sets` VALUES (184, 'stn_distract_kid_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (185, 'stn_crying_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (186, 'stn_onehand_relaxed_pipe_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (187, 'stn_onehand_relaxed_pipe_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (188, 'sit_chiar_kid', 0, '');
INSERT INTO `npc_posture_sets` VALUES (189, 'stn_anvil_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (190, 'stn_liabilities_b_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (191, 'stn_liabilities_c_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (192, 'stn_liabilities_d_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (193, 'sit_wounded_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (194, 'stn_tod_set_male_01', 97, '');
INSERT INTO `npc_posture_sets` VALUES (195, 'chair_crossleg_elf_03_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (196, 'stn_tod_set_female_02', 97, '');
INSERT INTO `npc_posture_sets` VALUES (197, 'stn_tod_set_all_03', 97, '');
INSERT INTO `npc_posture_sets` VALUES (198, 'fist_pos_gnd_corpse_lastwill_talking_test', 201, '');
INSERT INTO `npc_posture_sets` VALUES (199, 'stn_onehand_relaxed_dagger_all', 97, '');
INSERT INTO `npc_posture_sets` VALUES (200, 'stn_ax_all_notalk', 97, '장작패기');
INSERT INTO `npc_posture_sets` VALUES (201, 'chair_readbook_male(conductor)', 0, '원정대관리인');
INSERT INTO `npc_posture_sets` VALUES (202, 'pos_sit_pulling_plants_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (203, 'pos_sit_pulling_plants_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (204, 'sit_investigation_plants_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (205, 'sit_investigation_plants_male_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (206, 'chair_rest_all(higness)', 0, '');
INSERT INTO `npc_posture_sets` VALUES (207, 'stn_soldier_axe2_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (208, 'stn_search_cough_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (209, 'stn_priest_resurrection', 97, '');
INSERT INTO `npc_posture_sets` VALUES (210, 'stn_Honor_male', 0, '명예 점수 수집가');
INSERT INTO `npc_posture_sets` VALUES (211, 'stn_soldier_ferre_female_2', 97, '');
INSERT INTO `npc_posture_sets` VALUES (212, 'stn_ax_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (213, 'chair_straightleg2_female', 0, '');
INSERT INTO `npc_posture_sets` VALUES (214, 'chair_stump_oldman_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (215, 'stn_eatsuop_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (216, 'chair_eatsuop_all', 204, '');
INSERT INTO `npc_posture_sets` VALUES (217, 'stn_bored_all', 97, '');
INSERT INTO `npc_posture_sets` VALUES (218, 'stn_backpain_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (219, 'stn_guitarist_b_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (220, 'stn_shoveling_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (221, 'stn_onehand_relaxed_guitar_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (222, 'stn_onehand_relaxed_guitar_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (223, 'stn_guitarist_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (224, 'crouch_livestock_female', 0, '');
INSERT INTO `npc_posture_sets` VALUES (225, 'crouch_furniturerepair_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (226, 'stn_drink_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (227, 'chair_drink_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (228, 'stn_Honor_male_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (229, 'stn_commander_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (230, 'stn_soldier_sword_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (231, 'stn_anvil_all_test', 0, '');
INSERT INTO `npc_posture_sets` VALUES (232, 'stn_anvil_dwaf', 0, '');
INSERT INTO `npc_posture_sets` VALUES (233, 'stn_concierge_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (234, 'stn_ac_mine_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (235, 'stn_keeperflag_male', 0, '');
INSERT INTO `npc_posture_sets` VALUES (237, 'chair01_drink_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (239, 'sit_corch_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (240, 'chair_red_female', 0, '');
INSERT INTO `npc_posture_sets` VALUES (241, 'stn_cooking_all', 97, '');
INSERT INTO `npc_posture_sets` VALUES (242, 'stn_dance_all', 0, '댄스 \'밤의 열기\'');
INSERT INTO `npc_posture_sets` VALUES (243, 'stn_dance2_all', 0, '댄스 \'전쟁의 예고\'');
INSERT INTO `npc_posture_sets` VALUES (244, 'stn_tod_set_all_04', 0, '');
INSERT INTO `npc_posture_sets` VALUES (245, 'stn_onehand_ladle_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (246, 'stn_onehand_ladle_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (247, 'chair_drink_all(test)', 0, '스마트 오브젝트 테스트');
INSERT INTO `npc_posture_sets` VALUES (248, 'chair_drink_all(soc_test)', 0, '스마트 오브젝트 테스트 2');
INSERT INTO `npc_posture_sets` VALUES (249, 'chair02_drink_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (250, 'fishing_idle_all', 97, '');
INSERT INTO `npc_posture_sets` VALUES (251, 'fishing_action_all', 97, '');
INSERT INTO `npc_posture_sets` VALUES (252, 'stn_drink_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (253, 'stn_eatsuop_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (254, 'stn_onehand_relaxed_cane_all', 0, '');
INSERT INTO `npc_posture_sets` VALUES (255, 'stn_onehand_relaxed_cane_all_notalk', 97, '');
INSERT INTO `npc_posture_sets` VALUES (256, 'daru_warehousekeeper_notalk', 97, '다루 창고 관리인');
INSERT INTO `npc_posture_sets` VALUES (257, 'daru_traders_notalk', 97, '다루 교역상');
INSERT INTO `npc_posture_sets` VALUES (258, 'daru_pilot_notalk', 97, '순환 마차 관리인, 비행선 안내인');
INSERT INTO `npc_posture_sets` VALUES (259, 'daru_auctioneer_notalk', 97, '경매장 관리인, 신기루섬 안내인');
INSERT INTO `npc_posture_sets` VALUES (260, 'stn_anvil_dw_male', 0, '드워프 대장장이');
INSERT INTO `npc_posture_sets` VALUES (263, 'sit_beggar_notalk', 97, '');

-- ----------------------------
-- Table structure for npc_postures
-- ----------------------------
DROP TABLE IF EXISTS `npc_postures`;
CREATE TABLE `npc_postures`  (
  `id` int(10) UNSIGNED NOT NULL,
  `npc_posture_set_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT 'NPC动作集合ID',
  `anim_action_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT '动画ID',
  `talk_anim` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '谈话动作',
  `start_tod_time` tinyint(3) UNSIGNED NULL DEFAULT NULL COMMENT '启动时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of npc_postures
-- ----------------------------
INSERT INTO `npc_postures` VALUES (1, 1, 55, 'fist_pos_stn_stabler_talk', 0);
INSERT INTO `npc_postures` VALUES (3, 3, 92, 'fist_pos_sit_chair_weaponshop_dealer_talk', 0);
INSERT INTO `npc_postures` VALUES (4, 4, 54, '', 0);
INSERT INTO `npc_postures` VALUES (5, 5, 50, '', 0);
INSERT INTO `npc_postures` VALUES (6, 6, 101, 'fist_pos_stn_building_dealer_talk', 4);
INSERT INTO `npc_postures` VALUES (7, 7, 98, 'fist_pos_stn_soldier_mercenary_talk', 0);
INSERT INTO `npc_postures` VALUES (8, 8, 83, 'fist_pos_stn_handsback_talk', 0);
INSERT INTO `npc_postures` VALUES (9, 9, 39, 'fist_pos_priest_pray_talk', 0);
INSERT INTO `npc_postures` VALUES (11, 11, 37, 'fist_pos_record_talk', 0);
INSERT INTO `npc_postures` VALUES (12, 12, 54, 'fist_pos_stn_thinking_talk', 0);
INSERT INTO `npc_postures` VALUES (13, 13, 83, '', 0);
INSERT INTO `npc_postures` VALUES (14, 14, 50, 'fist_pos_stn_crossarm_talk', 0);
INSERT INTO `npc_postures` VALUES (15, 15, 113, '', 0);
INSERT INTO `npc_postures` VALUES (16, 16, 58, '', 0);
INSERT INTO `npc_postures` VALUES (17, 17, 26, 'fist_pos_sit_lean_talk', 0);
INSERT INTO `npc_postures` VALUES (19, 19, 106, 'fist_pos_stn_materials_trader_talk', 0);
INSERT INTO `npc_postures` VALUES (20, 20, 73, 'fist_pos_stn_pharmacist_talk', 0);
INSERT INTO `npc_postures` VALUES (21, 21, 103, 'fist_pos_record_talk', 0);
INSERT INTO `npc_postures` VALUES (22, 22, 87, 'fist_pos_sit_chair_nursery_dealer_talk', 0);
INSERT INTO `npc_postures` VALUES (23, 23, 224, 'fist_pos_sit_crouch_furniturerepair_talk', 0);
INSERT INTO `npc_postures` VALUES (24, 24, 100, 'fist_pos_stn_armor_dealer_talk', 0);
INSERT INTO `npc_postures` VALUES (25, 25, 40, 'fist_pos_priest_silent_talk', 0);
INSERT INTO `npc_postures` VALUES (26, 26, 30, 'fist_pos_dresser_talk', 0);
INSERT INTO `npc_postures` VALUES (27, 27, 223, 'fist_pos_sit_crouch_livestock_talk', 0);
INSERT INTO `npc_postures` VALUES (28, 28, 68, 'fist_pos_stn_florist_talk', 0);
INSERT INTO `npc_postures` VALUES (29, 29, 108, 'fist_pos_soldier_attention_talk', 0);
INSERT INTO `npc_postures` VALUES (30, 30, 113, 'fist_pos_stn_getherhands_talk', 0);
INSERT INTO `npc_postures` VALUES (31, 31, 106, '', 0);
INSERT INTO `npc_postures` VALUES (32, 32, 46, 'fist_ac_sexappeal', 0);
INSERT INTO `npc_postures` VALUES (33, 33, 47, 'fist_ac_temptation', 0);
INSERT INTO `npc_postures` VALUES (34, 34, 25, 'fist_pos_sit_crouch_talk', 0);
INSERT INTO `npc_postures` VALUES (35, 35, 81, 'fist_pos_sit_gnd_prisoner_talk', 0);
INSERT INTO `npc_postures` VALUES (36, 36, 72, 'fist_pos_stn_oldman_cane_talk', 0);
INSERT INTO `npc_postures` VALUES (37, 37, 27, 'fist_pos_sit_crossleg_talk', 0);
INSERT INTO `npc_postures` VALUES (38, 38, 65, 'fist_pos_sit_gnd_drunken_talk', 7);
INSERT INTO `npc_postures` VALUES (39, 39, 89, 'fist_pos_stn_cooking_soup_talk', 0);
INSERT INTO `npc_postures` VALUES (40, 40, 99, '', 0);
INSERT INTO `npc_postures` VALUES (41, 41, 105, 'fist_pos_sit_chair_talk', 4);
INSERT INTO `npc_postures` VALUES (42, 42, 104, 'fist_pos_stn_soldier_general_talk', 0);
INSERT INTO `npc_postures` VALUES (43, 43, 82, 'fist_pos_stn_soldier_mercenary_talk', 0);
INSERT INTO `npc_postures` VALUES (45, 45, 78, 'fist_pos_sit_chair_rest_talk', 4);
INSERT INTO `npc_postures` VALUES (47, 47, 20, 'fist_em_sleep', 0);
INSERT INTO `npc_postures` VALUES (48, 48, 61, 'fist_pos_sit_crouch_kid_talk', 0);
INSERT INTO `npc_postures` VALUES (49, 49, 75, 'fist_pos_sit_crouch_gang_talk', 0);
INSERT INTO `npc_postures` VALUES (50, 50, 56, 'fist_pos_sit_grd_netting_talk', 0);
INSERT INTO `npc_postures` VALUES (51, 51, 60, 'fist_pos_stn_sick_searching_talk', 0);
INSERT INTO `npc_postures` VALUES (52, 52, 59, 'fist_pos_sit_crouch_crying_idle', 0);
INSERT INTO `npc_postures` VALUES (53, 53, 70, 'fist_pos_sit_crouch_investigation_talk', 0);
INSERT INTO `npc_postures` VALUES (55, 55, 112, 'fist_pos_stn_soldier_guard_talk', 0);
INSERT INTO `npc_postures` VALUES (56, 56, 24, 'fist_pos_sit_chair_talk', 0);
INSERT INTO `npc_postures` VALUES (59, 59, 62, 'fist_pos_sit_crouch_kid_playing_talk', 0);
INSERT INTO `npc_postures` VALUES (60, 60, 76, 'fist_pos_corpse_1', 0);
INSERT INTO `npc_postures` VALUES (62, 62, 58, 'fist_pos_stn_searching_talk', 0);
INSERT INTO `npc_postures` VALUES (63, 63, 69, 'fist_pos_stn_soldier_archer_talk', 0);
INSERT INTO `npc_postures` VALUES (64, 64, 93, 'fist_pos_sit_chair_guitarist_tune_talk', 0);
INSERT INTO `npc_postures` VALUES (67, 67, 39, '', 0);
INSERT INTO `npc_postures` VALUES (68, 68, 80, '', 0);
INSERT INTO `npc_postures` VALUES (72, 72, 115, 'fist_pos_sit_chiar_talk', 0);
INSERT INTO `npc_postures` VALUES (73, 73, 79, 'fist_pos_sit_chair_talk', 0);
INSERT INTO `npc_postures` VALUES (78, 75, 109, 'fist_pos_soldier_attention_talk', 0);
INSERT INTO `npc_postures` VALUES (79, 76, 110, 'fist_pos_soldier_attention_talk', 0);
INSERT INTO `npc_postures` VALUES (80, 77, 111, 'fist_pos_soldier_attention_talk', 0);
INSERT INTO `npc_postures` VALUES (83, 83, 118, 'fist_ac_cough', 0);
INSERT INTO `npc_postures` VALUES (84, 84, 119, '', 0);
INSERT INTO `npc_postures` VALUES (85, 85, 120, '', 0);
INSERT INTO `npc_postures` VALUES (86, 86, 118, '', 0);
INSERT INTO `npc_postures` VALUES (87, 87, 121, 'fist_ac_falldown_loop', 0);
INSERT INTO `npc_postures` VALUES (88, 88, 122, '', 0);
INSERT INTO `npc_postures` VALUES (89, 89, 123, 'fist_ac_shoveling', 0);
INSERT INTO `npc_postures` VALUES (90, 90, 124, '', 0);
INSERT INTO `npc_postures` VALUES (91, 91, 125, '', 0);
INSERT INTO `npc_postures` VALUES (92, 92, 126, '', 0);
INSERT INTO `npc_postures` VALUES (93, 93, 126, '', 0);
INSERT INTO `npc_postures` VALUES (94, 94, 128, '', 0);
INSERT INTO `npc_postures` VALUES (95, 95, 129, '', 0);
INSERT INTO `npc_postures` VALUES (97, 97, 131, '', 0);
INSERT INTO `npc_postures` VALUES (98, 98, 132, 'fist_em_vomit', 0);
INSERT INTO `npc_postures` VALUES (99, 99, 133, 'fist_pos_stn_readbook_talk', 0);
INSERT INTO `npc_postures` VALUES (100, 79, 134, 'fsit_pos_stn_afraid_talk', 0);
INSERT INTO `npc_postures` VALUES (101, 78, 135, 'fist_pos_stn_angry_talk', 0);
INSERT INTO `npc_postures` VALUES (102, 81, 135, '', 0);
INSERT INTO `npc_postures` VALUES (103, 82, 134, '', 0);
INSERT INTO `npc_postures` VALUES (105, 100, 136, '', 0);
INSERT INTO `npc_postures` VALUES (106, 102, 137, '', 0);
INSERT INTO `npc_postures` VALUES (107, 103, 138, '', 0);
INSERT INTO `npc_postures` VALUES (108, 104, 139, '', 0);
INSERT INTO `npc_postures` VALUES (109, 105, 140, '', 0);
INSERT INTO `npc_postures` VALUES (110, 106, 141, 'fist_pos_sit_chair_rest_talk', 0);
INSERT INTO `npc_postures` VALUES (111, 107, 142, 'fist_pos_sit_crouch_investigation_talk', 0);
INSERT INTO `npc_postures` VALUES (112, 108, 143, 'fist_pos_record_talk', 0);
INSERT INTO `npc_postures` VALUES (113, 109, 144, 'fist_pos_sit_chair_pure_talk', 0);
INSERT INTO `npc_postures` VALUES (114, 110, 145, '', 0);
INSERT INTO `npc_postures` VALUES (115, 111, 146, 'fist_pos_stn_leanshovel_talk', 0);
INSERT INTO `npc_postures` VALUES (116, 112, 147, 'fist_pos_stn_peep_talk', 0);
INSERT INTO `npc_postures` VALUES (117, 113, 147, '', 0);
INSERT INTO `npc_postures` VALUES (118, 114, 148, 'fist_pos_stn_singing_talk', 0);
INSERT INTO `npc_postures` VALUES (119, 115, 148, '', 0);
INSERT INTO `npc_postures` VALUES (120, 116, 149, '', 0);
INSERT INTO `npc_postures` VALUES (121, 117, 63, 'fist_pos_sit_crouch_crying_talk', 0);
INSERT INTO `npc_postures` VALUES (122, 118, 63, '', 0);
INSERT INTO `npc_postures` VALUES (123, 119, 61, '', 0);
INSERT INTO `npc_postures` VALUES (124, 120, 62, '', 0);
INSERT INTO `npc_postures` VALUES (125, 121, 150, 'fist_pos_stn_anvil_talk', 0);
INSERT INTO `npc_postures` VALUES (126, 122, 155, 'fist_pos_gnd_sidesleep_talk', 0);
INSERT INTO `npc_postures` VALUES (127, 123, 157, 'fist_pos_stn_soldier_mercenary_talk', 0);
INSERT INTO `npc_postures` VALUES (128, 124, 158, 'fist_pos_stn_soldier_mercenary_talk', 0);
INSERT INTO `npc_postures` VALUES (129, 125, 159, 'fist_pos_sit_chair_talk', 0);
INSERT INTO `npc_postures` VALUES (130, 126, 160, 'fist_pos_sit_chair_talk', 0);
INSERT INTO `npc_postures` VALUES (131, 127, 161, 'fist_pos_sit_chair_crossleg_talk', 0);
INSERT INTO `npc_postures` VALUES (132, 128, 157, 'fist_pos_stn_soldier_mercenary_talk', 0);
INSERT INTO `npc_postures` VALUES (133, 129, 158, 'fist_pos_stn_soldier_mercenary_talk', 0);
INSERT INTO `npc_postures` VALUES (134, 130, 162, 'fist_pos_hang_prisoner_talk', 0);
INSERT INTO `npc_postures` VALUES (135, 131, 163, 'music_co_sk_lute_cast', 0);
INSERT INTO `npc_postures` VALUES (136, 133, 165, 'fist_pos_soldier_attention_talk', 0);
INSERT INTO `npc_postures` VALUES (137, 134, 166, 'fist_pos_soldier_attention_talk', 0);
INSERT INTO `npc_postures` VALUES (138, 135, 167, 'fist_pos_soldier_attention_talk', 0);
INSERT INTO `npc_postures` VALUES (139, 136, 168, 'fist_pos_soldier_attention_talk', 0);
INSERT INTO `npc_postures` VALUES (140, 137, 169, '', 0);
INSERT INTO `npc_postures` VALUES (141, 132, 164, 'music_co_sk_pipe_cast', 0);
INSERT INTO `npc_postures` VALUES (143, 139, 170, 'fist_pos_sit_chair_oldman_cane_talk', 0);
INSERT INTO `npc_postures` VALUES (145, 142, 171, 'fist_pos_stn_liabilities_talk', 0);
INSERT INTO `npc_postures` VALUES (146, 143, 172, '', 0);
INSERT INTO `npc_postures` VALUES (147, 144, 173, 'fist_pos_sit_chair_readbook_talk', 4);
INSERT INTO `npc_postures` VALUES (148, 145, 174, 'fist_pos_gnd_corpse_lastwill_talk', 0);
INSERT INTO `npc_postures` VALUES (149, 146, 203, 'fist_pos_stn_guitarist_talk', 0);
INSERT INTO `npc_postures` VALUES (150, 147, 176, 'fist_pos_sit_chair_armrest_talk', 0);
INSERT INTO `npc_postures` VALUES (151, 148, 177, 'fist_pos_stn_crossarm_talk', 0);
INSERT INTO `npc_postures` VALUES (152, 149, 177, '', 0);
INSERT INTO `npc_postures` VALUES (153, 150, 179, 'fist_pos_stn_cleaning_idle', 0);
INSERT INTO `npc_postures` VALUES (154, 151, 180, 'fist_pos_sit_chair_crossleg_talk', 4);
INSERT INTO `npc_postures` VALUES (155, 152, 125, 'fist_pos_stn_stumble_talk', 0);
INSERT INTO `npc_postures` VALUES (156, 153, 181, 'fist_pos_sit_chair_rest_talk', 0);
INSERT INTO `npc_postures` VALUES (157, 154, 182, 'fist_pos_sit_chair_crossleg_talk', 0);
INSERT INTO `npc_postures` VALUES (158, 155, 183, 'fist_pos_sit_chair_crossleg_talk', 0);
INSERT INTO `npc_postures` VALUES (159, 156, 184, 'fist_pos_sit_chair_crossleg_talk', 0);
INSERT INTO `npc_postures` VALUES (160, 157, 185, 'fist_pos_sit_chair_crossleg_talk', 0);
INSERT INTO `npc_postures` VALUES (162, 38, 155, 'fist_pos_gnd_sidesleep_talk', 20);
INSERT INTO `npc_postures` VALUES (163, 144, 160, 'fist_pos_sit_chair_talk', 20);
INSERT INTO `npc_postures` VALUES (164, 144, 160, 'fist_pos_sit_chair_talk', 0);
INSERT INTO `npc_postures` VALUES (167, 38, 155, 'fist_pos_gnd_sidesleep_talk', 0);
INSERT INTO `npc_postures` VALUES (168, 158, 186, 'fist_pos_sit_grd_netting_talk', 0);
INSERT INTO `npc_postures` VALUES (171, 151, 187, 'fist_pos_sit_chair_talk', 0);
INSERT INTO `npc_postures` VALUES (172, 151, 187, 'fist_pos_sit_chair_talk', 20);
INSERT INTO `npc_postures` VALUES (173, 159, 189, 'fist_pos_sit_chair_armrest_talk', 0);
INSERT INTO `npc_postures` VALUES (174, 160, 188, 'fist_pos_stn_onehand_relaxed_idle', 0);
INSERT INTO `npc_postures` VALUES (175, 161, 188, '', 0);
INSERT INTO `npc_postures` VALUES (176, 162, 190, 'fist_pos_stn_onehand_relaxed_idle(trowel01)', 0);
INSERT INTO `npc_postures` VALUES (177, 163, 190, '', 0);
INSERT INTO `npc_postures` VALUES (178, 164, 191, '', 0);
INSERT INTO `npc_postures` VALUES (179, 165, 191, '', 0);
INSERT INTO `npc_postures` VALUES (180, 166, 192, 'fist_pos_stn_onehand_relaxed_idle(bow_01_1 )', 0);
INSERT INTO `npc_postures` VALUES (181, 167, 192, '', 0);
INSERT INTO `npc_postures` VALUES (182, 168, 48, 'fist_ac_sprinklewater', 0);
INSERT INTO `npc_postures` VALUES (183, 169, 48, '', 0);
INSERT INTO `npc_postures` VALUES (184, 170, 49, 'fist_ac_get_fruit', 0);
INSERT INTO `npc_postures` VALUES (185, 171, 49, '', 0);
INSERT INTO `npc_postures` VALUES (186, 172, 74, 'fist_ac_feeding', 0);
INSERT INTO `npc_postures` VALUES (187, 173, 74, '', 0);
INSERT INTO `npc_postures` VALUES (188, 6, 79, 'fist_pos_sit_chair_sleep_talk', 0);
INSERT INTO `npc_postures` VALUES (189, 6, 79, 'fist_pos_sit_chair_sleep_talk', 20);
INSERT INTO `npc_postures` VALUES (190, 174, 55, '', 0);
INSERT INTO `npc_postures` VALUES (191, 175, 179, '', 0);
INSERT INTO `npc_postures` VALUES (192, 41, 160, 'fist_pos_sit_chair_talk', 0);
INSERT INTO `npc_postures` VALUES (193, 41, 160, 'fist_pos_sit_chair_talk', 20);
INSERT INTO `npc_postures` VALUES (194, 176, 68, '', 0);
INSERT INTO `npc_postures` VALUES (195, 177, 194, 'fist_pos_stn_liabilities_talk', 0);
INSERT INTO `npc_postures` VALUES (196, 179, 195, 'fist_pos_stn_liabilities_talk', 0);
INSERT INTO `npc_postures` VALUES (197, 180, 196, 'fist_pos_stn_onehand_relaxed_idle(lamp)', 0);
INSERT INTO `npc_postures` VALUES (198, 181, 196, '', 0);
INSERT INTO `npc_postures` VALUES (199, 182, 149, 'fist_pos_stn_shy_talk', 0);
INSERT INTO `npc_postures` VALUES (200, 183, 193, 'fist_pos_stn_distract_talk', 0);
INSERT INTO `npc_postures` VALUES (201, 184, 193, '', 0);
INSERT INTO `npc_postures` VALUES (202, 185, 140, 'fist_pos_stn_crying_talk', 0);
INSERT INTO `npc_postures` VALUES (203, 186, 197, 'fist_pos_stn_onehand_relaxed_idle(ins_w_16_1)', 0);
INSERT INTO `npc_postures` VALUES (204, 187, 197, '', 0);
INSERT INTO `npc_postures` VALUES (205, 188, 198, 'fist_pos_sit_chair_talk', 0);
INSERT INTO `npc_postures` VALUES (206, 189, 150, '', 0);
INSERT INTO `npc_postures` VALUES (207, 190, 171, '', 0);
INSERT INTO `npc_postures` VALUES (208, 191, 194, '', 0);
INSERT INTO `npc_postures` VALUES (209, 192, 195, '', 0);
INSERT INTO `npc_postures` VALUES (210, 193, 199, 'fist_pos_sit_gnd_wounded_talk', 0);
INSERT INTO `npc_postures` VALUES (211, 194, 83, '', 3);
INSERT INTO `npc_postures` VALUES (212, 194, 196, '', 20);
INSERT INTO `npc_postures` VALUES (213, 194, 196, '', 0);
INSERT INTO `npc_postures` VALUES (214, 195, 200, 'fist_pos_sit_chair_rest_talk', 0);
INSERT INTO `npc_postures` VALUES (215, 196, 196, '', 0);
INSERT INTO `npc_postures` VALUES (216, 196, 113, '', 3);
INSERT INTO `npc_postures` VALUES (217, 196, 196, '', 20);
INSERT INTO `npc_postures` VALUES (218, 197, 179, '', 3);
INSERT INTO `npc_postures` VALUES (219, 197, 196, '', 0);
INSERT INTO `npc_postures` VALUES (220, 197, 196, '', 20);
INSERT INTO `npc_postures` VALUES (221, 198, 174, 'fist_pos_gnd_corpse_lastwill_talking_talk', 0);
INSERT INTO `npc_postures` VALUES (222, 199, 202, '', 0);
INSERT INTO `npc_postures` VALUES (224, 45, 160, 'fist_pos_sit_chair_talk', 0);
INSERT INTO `npc_postures` VALUES (225, 45, 160, 'fist_pos_sit_chair_talk', 20);
INSERT INTO `npc_postures` VALUES (226, 200, 205, '', 0);
INSERT INTO `npc_postures` VALUES (227, 201, 206, 'fist_pos_sit_chair_readbook_talk', 0);
INSERT INTO `npc_postures` VALUES (228, 202, 207, 'fist_ac_pulling', 0);
INSERT INTO `npc_postures` VALUES (229, 203, 207, '', 0);
INSERT INTO `npc_postures` VALUES (230, 204, 208, 'fist_pos_sit_crouch_investigation_talk', 0);
INSERT INTO `npc_postures` VALUES (231, 205, 208, '', 0);
INSERT INTO `npc_postures` VALUES (232, 206, 209, 'fist_pos_sit_chair_rest_talk', 0);
INSERT INTO `npc_postures` VALUES (233, 207, 210, 'fist_pos_stn_soldier_mercenary_talk', 0);
INSERT INTO `npc_postures` VALUES (234, 208, 60, '', 0);
INSERT INTO `npc_postures` VALUES (235, 209, 213, 'fist_pos_priest_resurrection_talk', 0);
INSERT INTO `npc_postures` VALUES (236, 210, 214, 'fist_pos_stn_soldier_mercenary_talk', 0);
INSERT INTO `npc_postures` VALUES (238, 212, 205, 'fist_ac_mine(Ax)', 0);
INSERT INTO `npc_postures` VALUES (239, 213, 216, 'fist_pos_sit_chair_pure_talk', 0);
INSERT INTO `npc_postures` VALUES (240, 214, 217, 'fist_pos_sit_chair_oldman_cane_talk', 0);
INSERT INTO `npc_postures` VALUES (241, 215, 218, 'fist_pos_stn_eatsuop_talk', 0);
INSERT INTO `npc_postures` VALUES (242, 216, 219, 'fist_pos_sit_chair_eatsuop_talk', 0);
INSERT INTO `npc_postures` VALUES (243, 217, 220, '', 0);
INSERT INTO `npc_postures` VALUES (244, 218, 221, '', 0);
INSERT INTO `npc_postures` VALUES (245, 219, 175, '', 0);
INSERT INTO `npc_postures` VALUES (246, 220, 146, '', 0);
INSERT INTO `npc_postures` VALUES (247, 221, 222, 'fist_pos_stn_onehand_relaxed_idle(guitar)', 0);
INSERT INTO `npc_postures` VALUES (248, 222, 222, '', 0);
INSERT INTO `npc_postures` VALUES (249, 223, 203, '', 0);
INSERT INTO `npc_postures` VALUES (250, 224, 223, 'fist_pos_sit_crouch_livestock_talk', 0);
INSERT INTO `npc_postures` VALUES (251, 225, 224, 'fist_pos_sit_crouch_furniturerepair_talk', 0);
INSERT INTO `npc_postures` VALUES (252, 226, 225, 'fist_pos_stn_drink_talk', 0);
INSERT INTO `npc_postures` VALUES (253, 227, 226, 'fist_pos_sit_chair_drink_talk', 0);
INSERT INTO `npc_postures` VALUES (254, 228, 214, '', 0);
INSERT INTO `npc_postures` VALUES (255, 229, 104, '', 0);
INSERT INTO `npc_postures` VALUES (256, 230, 112, '', 0);
INSERT INTO `npc_postures` VALUES (257, 231, 227, 'fist_pos_stn_anvil_talk', 0);
INSERT INTO `npc_postures` VALUES (258, 232, 228, '', 0);
INSERT INTO `npc_postures` VALUES (259, 233, 28, 'fist_pos_soldier_attention_talk', 0);
INSERT INTO `npc_postures` VALUES (260, 234, 232, 'fist_ac_mine(Miners)', 0);
INSERT INTO `npc_postures` VALUES (261, 235, 233, 'fist_pos_stn_keeperflag_talk', 0);
INSERT INTO `npc_postures` VALUES (263, 237, 235, 'fist_pos_sit_chair_drink_talk', 0);
INSERT INTO `npc_postures` VALUES (265, 239, 25, '', 0);
INSERT INTO `npc_postures` VALUES (266, 240, 236, 'fist_pos_sit_chair_pure_talk', 0);
INSERT INTO `npc_postures` VALUES (267, 241, 237, '', 0);
INSERT INTO `npc_postures` VALUES (268, 242, 238, 'fist_ba_dance_idle', 0);
INSERT INTO `npc_postures` VALUES (269, 243, 239, 'fist_ba_dance2_idle', 0);
INSERT INTO `npc_postures` VALUES (270, 244, 125, 'fist_pos_stn_stumble_talk', 0);
INSERT INTO `npc_postures` VALUES (271, 244, 225, 'fist_pos_stn_drink_idle', 7);
INSERT INTO `npc_postures` VALUES (272, 244, 125, 'fist_pos_stn_stumble_talk', 20);
INSERT INTO `npc_postures` VALUES (273, 245, 240, 'fist_pos_stn_onehand_relaxed_idle(ladle)', 0);
INSERT INTO `npc_postures` VALUES (274, 246, 240, '', 0);
INSERT INTO `npc_postures` VALUES (275, 247, 243, 'fist_pos_sit_chair_drink_talk', 0);
INSERT INTO `npc_postures` VALUES (277, 249, 244, 'fist_pos_sit_chair_drink_talk', 0);
INSERT INTO `npc_postures` VALUES (278, 250, 245, '', 0);
INSERT INTO `npc_postures` VALUES (279, 251, 247, '', 0);
INSERT INTO `npc_postures` VALUES (280, 252, 225, '', 0);
INSERT INTO `npc_postures` VALUES (281, 253, 218, '', 0);
INSERT INTO `npc_postures` VALUES (282, 254, 250, 'fist_pos_stn_onehand_relaxed_idle(Cane)', 0);
INSERT INTO `npc_postures` VALUES (283, 255, 250, '', 0);
INSERT INTO `npc_postures` VALUES (284, 256, 252, '', 0);
INSERT INTO `npc_postures` VALUES (285, 257, 253, '', 0);
INSERT INTO `npc_postures` VALUES (286, 258, 254, '', 0);
INSERT INTO `npc_postures` VALUES (287, 259, 255, '', 0);
INSERT INTO `npc_postures` VALUES (288, 260, 256, 'fist_pos_stn_anvil_talk', 0);
INSERT INTO `npc_postures` VALUES (291, 263, 120, '', 0);

SET FOREIGN_KEY_CHECKS = 1;
